# Generated by Django 4.0.1 on 2022-01-19 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_character_profession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-power']},
        ),
        migrations.AlterField(
            model_name='character',
            name='base_stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.stats'),
        ),
        migrations.AlterField(
            model_name='character',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Common'), (2, 'Rare'), (3, 'Epic'), (4, 'Mythic'), (5, 'Legendary')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Common'), (2, 'Rare'), (3, 'Epic'), (4, 'Mythic'), (5, 'Legendary')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userresources',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.Item'),
        ),
    ]
