# Generated by Django 4.0.1 on 2022-01-24 20:57

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_experience_user_gold_user_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresources',
            name='characters',
            field=models.ManyToManyField(blank=True, to='core.Character'),
        ),
        migrations.AlterField(
            model_name='userresources',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
