# Generated by Django 4.0.1 on 2022-01-30 14:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chest_store_itemchest_characterchest'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.character_image_file_path),
        ),
    ]
