# Generated by Django 4.0.1 on 2022-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lvl',
        ),
        migrations.AddField(
            model_name='userresources',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresources',
            name='gold',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userresources',
            name='lvl',
            field=models.IntegerField(default=1),
        ),
    ]
