# Generated by Django 4.0.1 on 2022-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_experience_remove_user_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lvl_required', models.IntegerField()),
                ('gold_reward', models.IntegerField()),
                ('exp_reward', models.IntegerField()),
                ('character_reward', models.ManyToManyField(null=True, to='core.Character')),
                ('item_reward', models.ManyToManyField(null=True, to='core.Item')),
            ],
        ),
    ]
