# Generated by Django 4.0.1 on 2022-02-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_availablequest_quest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablequest',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='availablequest',
            name='completed',
        ),
        migrations.AddField(
            model_name='availablequest',
            name='completed',
            field=models.ManyToManyField(to='core.Quest'),
        ),
    ]
