# Generated by Django 4.0.1 on 2022-02-06 17:22

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_availablequest_quest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablequest',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
