# Generated by Django 4.0.1 on 2022-02-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quest_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('min_exp', models.IntegerField()),
                ('max_exp', models.IntegerField()),
                ('loot_chance', models.IntegerField()),
                ('loot', models.ManyToManyField(blank=True, to='core.Item')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stats')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enemies', models.ManyToManyField(to='core.Enemy')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rooms', models.ManyToManyField(to='core.Room')),
            ],
        ),
    ]
